# Generated by Django 3.2.4 on 2021-06-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_notes', '0003_notes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='images'),
        ),
    ]
